# Generated by Django 6.0.6 on 2026-08-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VeiculoFrota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True, verbose_name='Placa')),
                ('renavam', models.CharField(blank=True, default='', max_length=20, verbose_name='RENAVAM')),
                ('chassi', models.CharField(blank=True, default='', max_length=30, verbose_name='Chassi')),
                ('marca', models.CharField(max_length=80, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=120, verbose_name='Modelo')),
                ('ano_fabricacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de fabricação')),
                ('ano_modelo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano modelo')),
                ('cor', models.CharField(blank=True, default='', max_length=40, verbose_name='Cor')),
                ('combustivel', models.CharField(choices=[('diesel', 'Diesel'), ('gasolina', 'Gasolina'), ('etanol', 'Etanol'), ('flex', 'Flex'), ('gnv', 'GNV'), ('eletrico', 'Elétrico')], default='diesel', max_length=20, verbose_name='Combustível')),
                ('categoria', models.CharField(choices=[('caminhao', 'Caminhão'), ('cavalo', 'Cavalo mecânico'), ('carreta', 'Carreta'), ('van', 'Van'), ('utilitario', 'Utilitário'), ('automovel', 'Automóvel'), ('onibus', 'Ônibus'), ('outro', 'Outro')], default='caminhao', max_length=20, verbose_name='Categoria')),
                ('hodometro', models.PositiveIntegerField(default=0, verbose_name='Hodômetro (km)')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10, verbose_name='Status')),
                ('filial', models.CharField(choices=[('Ibiporã (Matriz)', 'Ibiporã (Matriz)'), ('Rondonópolis', 'Rondonópolis'), ('Paranaguá', 'Paranaguá')], max_length=80, verbose_name='Filial')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo da frota',
                'verbose_name_plural': 'Veículos da frota',
                'ordering': ['placa'],
            },
        ),
    ]
