# Generated by Django 6.0.6 on 2026-08-31 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0003_multa_planilha_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustoFrotaLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('imported_manutencao', models.BooleanField(default=False)),
                ('imported_abastecimento', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_custo_frota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de custos da frota',
                'verbose_name_plural': 'Lotes de custos da frota',
                'ordering': ['-periodo_inicio', '-created_at'],
                'unique_together': {('periodo_inicio', 'periodo_fim')},
            },
        ),
        migrations.CreateModel(
            name='CustoAbastecimentoLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8)),
                ('transacao', models.CharField(blank=True, default='', max_length=40)),
                ('data', models.DateField(blank=True, null=True)),
                ('hora', models.CharField(blank=True, default='', max_length=20)),
                ('estabelecimento', models.CharField(blank=True, default='', max_length=200)),
                ('cidade', models.CharField(blank=True, default='', max_length=120)),
                ('motorista', models.CharField(blank=True, default='', max_length=150)),
                ('hodometro', models.PositiveIntegerField(blank=True, null=True)),
                ('litragem', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('combustivel', models.CharField(blank=True, default='', max_length=40)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('numero_nfe', models.CharField(blank=True, default='', max_length=40)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custos_abastecimento', to='frota.veiculofrota')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimento_linhas', to='frota.custofrotalote')),
            ],
            options={
                'ordering': ['-data', 'placa'],
            },
        ),
        migrations.CreateModel(
            name='CustoManutencaoLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8)),
                ('grupo', models.CharField(blank=True, default='', max_length=120)),
                ('item', models.CharField(max_length=200)),
                ('valor_material', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_servicos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencao_linhas', to='frota.custofrotalote')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custos_manutencao', to='frota.veiculofrota')),
            ],
            options={
                'ordering': ['placa', 'item'],
            },
        ),
    ]
