# Generated by Django 6.0.6 on 2026-06-11 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('reference_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('imported_pagar', models.BooleanField(default=False)),
                ('imported_receber', models.BooleanField(default=False)),
                ('imported_aging', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reference_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceberTitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=100)),
                ('cod_cliente', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=50)),
                ('natureza', models.CharField(max_length=20)),
                ('emissao', models.CharField(max_length=20)),
                ('vencimento', models.CharField(max_length=20)),
                ('vencimento_real', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('historico', models.CharField(blank=True, max_length=500)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receber_rows', to='financeiro.reportbatch')),
            ],
            options={
                'ordering': ['filial', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='PagarTitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=100)),
                ('cod_forn', models.CharField(max_length=50)),
                ('fornecedor', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=20)),
                ('emissao', models.CharField(max_length=20)),
                ('vencimento', models.CharField(max_length=20)),
                ('vencimento_real', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('historico', models.CharField(blank=True, max_length=500)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagar_rows', to='financeiro.reportbatch')),
            ],
            options={
                'ordering': ['filial', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='AgingTitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=100)),
                ('cod_cliente', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=200)),
                ('loja', models.CharField(max_length=20)),
                ('docto', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('emissao', models.CharField(max_length=20)),
                ('vencimento', models.CharField(max_length=20)),
                ('regiao', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aging_rows', to='financeiro.reportbatch')),
            ],
            options={
                'ordering': ['origem', 'docto'],
            },
        ),
    ]
