# Generated by Django 6.0.6 on 2026-06-11 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=100)),
                ('agency', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('account_type', models.CharField(max_length=30)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_updated', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['bank', 'number'],
            },
        ),
        migrations.CreateModel(
            name='CashAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField()),
                ('adjustment_type', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observation', models.TextField()),
                ('created_by', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-reference_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BalanceHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField()),
                ('bank', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=30)),
                ('entry_type', models.CharField(max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='financeiro.bankaccount')),
            ],
            options={
                'ordering': ['-reference_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField()),
                ('branch', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Transmitida', 'Transmitida'), ('Pendente', 'Pendente'), ('Cancelada', 'Cancelada')], default='Transmitida', max_length=20)),
            ],
            options={
                'ordering': ['-reference_date', 'branch'],
                'unique_together': {('reference_date', 'branch')},
            },
        ),
    ]
