# Generated by Django 6.0.6 on 2026-06-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_bankaccount_cashadjustment_balancehistoryentry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingrecord',
            name='status',
        ),
    ]
