# Generated by Django 6.0.6 on 2026-06-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_remove_billingrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='last_updated',
            field=models.CharField(default='--/--/----', max_length=30),
        ),
    ]
