# Generated by Django 5.2.16 on 2026-07-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_pagartitulo_pr_desconsiderada'),
    ]

    operations = [
        migrations.CreateModel(
            name='GnreIcmsOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=50)),
                ('cte', models.CharField(max_length=50)),
                ('valor_guia', models.DecimalField(decimal_places=2, max_digits=14)),
                ('periodo_referencia', models.CharField(max_length=20)),
                ('data_pagamento', models.DateField()),
                ('validada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GNRE-ICMS (ocorrência)',
                'verbose_name_plural': 'GNRE-ICMS (ocorrências)',
                'ordering': ['-data_pagamento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotaPagaSemLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=50)),
                ('nfs', models.CharField(max_length=50)),
                ('fornecedor', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data_emissao', models.DateField()),
                ('envio_provisao_luft', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField()),
                ('justificativa', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nota paga sem lançamento',
                'verbose_name_plural': 'Notas pagas sem lançamento',
                'ordering': ['-data_pagamento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OpsRecebidaOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=50)),
                ('contrato', models.CharField(max_length=50)),
                ('data_pagamento', models.DateField()),
                ('mdfe_encerrado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OP recebida (ocorrência)',
                'verbose_name_plural': 'OPs recebidas (ocorrências)',
                'ordering': ['-data_pagamento', '-id'],
            },
        ),
    ]
