# Generated by Django 6.0.6 on 2026-10-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_calendarioevento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixinhaLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField()),
                ('movement_type', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(max_length=300)),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['-reference_date', '-id'],
            },
        ),
    ]
