# Generated by Django 6.0.6 on 2026-06-29 14:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255, unique=True, verbose_name='Cargo')),
                ('categoria', models.CharField(blank=True, choices=[('ADMINISTRATIVO', 'Administrativo'), ('OPERACIONAL', 'Operacional'), ('MOTORISTA', 'Motorista')], max_length=50, null=True, verbose_name='Categoria')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mapeamento de Cargo',
                'verbose_name_plural': 'Mapeamentos de Cargos',
                'ordering': ['cargo'],
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='C.P.F.')),
                ('matricula', models.CharField(max_length=20, verbose_name='Matrícula')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('filial', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('situacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Situação')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='Data Adm.')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='Data Dem.')),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('nome_lider', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Líder')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data Nasc.')),
                ('escolaridade', models.CharField(blank=True, max_length=255, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo')),
                ('regime', models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'PJ')], default='CLT', max_length=10, verbose_name='Regime')),
                ('categoria', models.CharField(blank=True, choices=[('ADMINISTRATIVO', 'Administrativo'), ('OPERACIONAL', 'Operacional'), ('MOTORISTA', 'Motorista')], max_length=50, null=True, verbose_name='Categoria')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('desconsiderado', models.BooleanField(default=False, verbose_name='Desconsiderar em Indicadores')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='ColaboradorPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salário')),
                ('filial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Filial')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='Data Adm.')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data Nasc.')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PJ Cadastrado',
                'verbose_name_plural': 'PJs Cadastrados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LoteMovimentacaoRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('data_importacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Importação')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='rh/movimentacoes/%Y/%m/', verbose_name='Arquivo Excel')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Lote de Movimentação RH',
                'verbose_name_plural': 'Lotes de Movimentação RH',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='InconsistenciaColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('salario', 'Aumento de Salário'), ('cargo', 'Alteração de Cargo'), ('outros', 'Outros')], default='salario', max_length=20, verbose_name='Tipo')),
                ('valor_anterior', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor Anterior')),
                ('valor_atual', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor Atual')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inconsistencias', to='rh.lotemovimentacaorh', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Alteração de Colaborador',
                'verbose_name_plural': 'Alterações de Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Filial')),
                ('nome', models.CharField(max_length=255, verbose_name='Funcionário/Nome')),
                ('situacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status do Funcionário')),
                ('uf_estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='UF/Estado')),
                ('funcao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Função')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='Admissão')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Nascimento')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('pis_pasep', models.CharField(blank=True, max_length=20, null=True, verbose_name='PIS/PASEP')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salário')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoria')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='rh.lotemovimentacaorh', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Movimentação de Colaborador',
                'verbose_name_plural': 'Movimentações de Colaboradores',
                'indexes': [models.Index(fields=['cpf'], name='rh_moviment_cpf_4f60dc_idx'), models.Index(fields=['lote'], name='rh_moviment_lote_id_e9d982_idx')],
            },
        ),
    ]
