# Generated by Django 6.0.6 on 2026-10-09 12:21

import apps.camilo.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camilo', '0005_termo_versao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PastaMatrizEmpresarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpastas', to='camilo.pastamatrizempresarial')),
            ],
            options={
                'verbose_name': 'Pasta da Matriz empresarial',
                'verbose_name_plural': 'Pastas da Matriz empresarial',
                'ordering': ['nome', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoMatrizEmpresarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('arquivo', models.FileField(blank=True, upload_to=apps.camilo.models.documento_matriz_empresarial_upload_path)),
                ('drive_file_id', models.CharField(blank=True, default='', max_length=128)),
                ('link_externo', models.CharField(blank=True, default='', max_length=500)),
                ('nome_original', models.CharField(max_length=180)),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('texto', models.TextField(blank=True, default='')),
                ('texto_extraido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('incluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_matriz_empresarial', to=settings.AUTH_USER_MODEL)),
                ('pasta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='camilo.pastamatrizempresarial')),
            ],
            options={
                'verbose_name': 'Documento da Matriz empresarial',
                'verbose_name_plural': 'Documentos da Matriz empresarial',
                'ordering': ['-criado_em'],
            },
        ),
    ]
