# Generated by Django 5.2.16 on 2026-09-29 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.CharField(blank=True, default='', max_length=40)),
                ('tipo', models.CharField(db_index=True, max_length=80)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField(blank=True, default='')),
                ('link', models.CharField(blank=True, default='', max_length=300, verbose_name='Rota no ERP')),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criada_em', '-id'],
                'indexes': [models.Index(fields=['usuario', 'lida_em'], name='notif_usuario_lida_idx')],
            },
        ),
    ]
