# Generated by Django 5.2.16 on 2026-09-29 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0002_push_inscricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['criada_em'], name='notif_criada_idx'),
        ),
    ]
