# Generated by Django 5.2.16 on 2026-07-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PesquisaSatisfacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorista', models.CharField(max_length=255, verbose_name='Motorista')),
                ('cte', models.CharField(max_length=50, verbose_name='CT-e')),
                ('data', models.DateField(verbose_name='Data')),
                ('nota_fiscal', models.CharField(max_length=50, verbose_name='Nota Fiscal')),
                ('cliente', models.CharField(choices=[('CCAB', 'CCAB'), ('PRENTISS', 'PRENTISS'), ('ALBAUGH', 'ALBAUGH'), ('UPL', 'UPL'), ('OUTROS', 'OUTROS')], default='OUTROS', max_length=20, verbose_name='Cliente')),
                ('prazo_entrega', models.CharField(choices=[('otimo', 'Ótimo'), ('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim')], max_length=10, verbose_name='Prazo de Entrega')),
                ('condicoes_mercadoria', models.CharField(choices=[('otimo', 'Ótimo'), ('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim')], max_length=10, verbose_name='Condições da Mercadoria')),
                ('condicoes_veiculo', models.CharField(choices=[('otimo', 'Ótimo'), ('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim')], max_length=10, verbose_name='Condições do Veículo')),
                ('apresentacao_motorista', models.CharField(choices=[('otimo', 'Ótimo'), ('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim')], max_length=10, verbose_name='Apresentação do Motorista')),
                ('atendimento_dispensado', models.CharField(choices=[('otimo', 'Ótimo'), ('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim')], max_length=10, verbose_name='Atendimento Dispensado')),
                ('analise', models.TextField(blank=True, default='', verbose_name='Análise')),
                ('tratativa_justificativa', models.TextField(blank=True, default='', verbose_name='Tratativa e Justificativa')),
                ('criado_por', models.CharField(blank=True, default='', max_length=150, verbose_name='Criado por')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pesquisa de Satisfação',
                'verbose_name_plural': 'Pesquisas de Satisfação',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
