# Generated by Django 6.0.6 on 2026-07-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='filial',
            field=models.CharField(default='Ibiporã (Matriz)', max_length=100, verbose_name='Filial'),
        ),
    ]
