# Generated by Django 6.0.6 on 2026-07-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgq', '0002_pesquisasatisfacao_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='cliente_recusou_assinar',
            field=models.BooleanField(default=False, verbose_name='Cliente recusou assinar'),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='apresentacao_motorista',
            field=models.CharField(blank=True, choices=[('otimo', 'Ótimo'), ('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim')], default='', max_length=10, verbose_name='Apresentação do Motorista'),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='atendimento_dispensado',
            field=models.CharField(blank=True, choices=[('otimo', 'Ótimo'), ('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim')], default='', max_length=10, verbose_name='Atendimento Dispensado'),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='condicoes_mercadoria',
            field=models.CharField(blank=True, choices=[('otimo', 'Ótimo'), ('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim')], default='', max_length=10, verbose_name='Condições da Mercadoria'),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='condicoes_veiculo',
            field=models.CharField(blank=True, choices=[('otimo', 'Ótimo'), ('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim')], default='', max_length=10, verbose_name='Condições do Veículo'),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='prazo_entrega',
            field=models.CharField(blank=True, choices=[('otimo', 'Ótimo'), ('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim')], default='', max_length=10, verbose_name='Prazo de Entrega'),
        ),
    ]
