# Generated by Django 6.0.6 on 2026-07-29 16:45

from django.db import migrations, models


def merge_tratativa_into_analise(apps, schema_editor):
    """Antes de remover a coluna, junta o texto de 'Tratativa e Justificativa'
    dentro de 'Análise' (agora campo único), sem perder dados já preenchidos."""
    PesquisaSatisfacao = apps.get_model('sgq', 'PesquisaSatisfacao')
    for pesquisa in PesquisaSatisfacao.objects.exclude(tratativa_justificativa=''):
        partes = [p for p in (pesquisa.analise or '', pesquisa.tratativa_justificativa or '') if p]
        pesquisa.analise = '\n\n'.join(partes)
        pesquisa.save(update_fields=['analise'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sgq', '0003_pesquisasatisfacao_cliente_recusou_assinar_and_more'),
    ]

    operations = [
        migrations.RunPython(merge_tratativa_into_analise, noop_reverse),
        migrations.RemoveField(
            model_name='pesquisasatisfacao',
            name='tratativa_justificativa',
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='analise',
            field=models.TextField(blank=True, default='', verbose_name='Análise, Tratativa e Justificativa'),
        ),
    ]
