# Generated by Django 6.0.6 on 2026-07-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgq', '0005_data_entrega_e_data_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='cliente',
            field=models.CharField(choices=[('CCAB', 'CCAB'), ('PRENTISS', 'PRENTISS'), ('ALBAUGH', 'ALBAUGH'), ('OUTROS', 'OUTROS')], default='OUTROS', max_length=20, verbose_name='Cliente'),
        ),
    ]
