# Generated by Django 6.0.6 on 2026-07-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgq', '0007_rename_data_envio_to_data_inclusao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(default='Ibiporã (Matriz)', max_length=100, verbose_name='Filial')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('setor', models.CharField(choices=[('qualidade', 'Qualidade'), ('operacao', 'Operação'), ('frota', 'Frota'), ('administrativo', 'Administrativo'), ('comercial', 'Comercial')], max_length=30, verbose_name='Setor')),
                ('canvas', models.JSONField(blank=True, default=dict, verbose_name='Canvas')),
                ('criado_por', models.CharField(blank=True, default='', max_length=150, verbose_name='Criado por')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fluxo de Trabalho',
                'verbose_name_plural': 'Fluxos de Trabalho',
                'ordering': ['-data_atualizacao', '-id'],
            },
        ),
    ]
