# Generated by Django 6.0.6 on 2026-07-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgq', '0008_fluxo_trabalho'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FluxoTrabalho',
        ),
    ]
