# Generated by Django 6.0.6 on 2026-07-30 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgq', '0009_remove_fluxo_trabalho'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PesquisaSatisfacaoLoteDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=100)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('rows', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sgq_lote_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rascunho de Inclusão em Tabela',
                'verbose_name_plural': 'Rascunhos de Inclusão em Tabela',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'filial'), name='uniq_sgq_lote_draft_usuario_filial')],
            },
        ),
    ]
