# Generated by Django 6.0.6 on 2026-08-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgq', '0010_pesquisasatisfacaolotedraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='cte',
            field=models.CharField(max_length=500, verbose_name='CT-e'),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='nota_fiscal',
            field=models.CharField(max_length=500, verbose_name='Nota Fiscal'),
        ),
    ]
