# Generated by Django 6.0.6 on 2026-07-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0002_remove_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocoloenvio',
            name='expedicao',
            field=models.CharField(blank=True, choices=[('Transcamila Ibiporã', 'Transcamila Ibiporã'), ('Transcamila Barueri', 'Transcamila Barueri'), ('Transcamila Paranaguá', 'Transcamila Paranaguá'), ('Transcamila Rondonópolis', 'Transcamila Rondonópolis')], max_length=50, null=True, verbose_name='Expedição'),
        ),
        migrations.AlterField(
            model_name='protocoloenvio',
            name='nota_fiscal',
            field=models.TextField(help_text='Números das NFs separados por vírgula (até 72)'),
        ),
    ]
