# Generated by Django 6.0.6 on 2026-07-13 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0003_alter_protocoloenvio_expedicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteprotocolo',
            name='exige_filial',
            field=models.BooleanField(default=False, verbose_name='Exigir filial do cliente?'),
        ),
        migrations.AddField(
            model_name='protocoloenvio',
            name='notas_filiais',
            field=models.JSONField(blank=True, default=dict, help_text='Mapeamento {número_NF: nome_filial} quando o cliente exige filial', verbose_name='NFs por filial'),
        ),
        migrations.CreateModel(
            name='FilialClienteProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da filial')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiais', to='faturamento.clienteprotocolo', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Filial de cliente de protocolo',
                'verbose_name_plural': 'Filiais de cliente de protocolo',
                'ordering': ['nome'],
                'unique_together': {('cliente', 'nome')},
            },
        ),
    ]
