# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0004_clienteprotocolo_exige_filial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocoloenvio',
            name='expedicao',
            field=models.CharField(
                blank=True,
                help_text='Valor final, podendo combinar até 2 expedições (ex.: "Transcamila Barueri/Ibiporã")',
                max_length=100,
                null=True,
                verbose_name='Expedição',
            ),
        ),
    ]
