# Generated by Django 6.0.6

from django.db import migrations, models


def backfill_numero_sequencial(apps, schema_editor):
    ClienteProtocolo = apps.get_model('faturamento', 'ClienteProtocolo')
    ProtocoloEnvio = apps.get_model('faturamento', 'ProtocoloEnvio')
    for cliente in ClienteProtocolo.objects.all():
        protocolos = ProtocoloEnvio.objects.filter(cliente=cliente).order_by('data_criacao', 'pk')
        contador = 0
        for protocolo in protocolos:
            contador += 1
            protocolo.numero_sequencial = contador
            protocolo.save(update_fields=['numero_sequencial'])
        cliente.ultimo_numero_protocolo = contador
        cliente.save(update_fields=['ultimo_numero_protocolo'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0005_alter_protocoloenvio_expedicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteprotocolo',
            name='ultimo_numero_protocolo',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Controla a sequência numérica de protocolos deste cliente (cada cliente tem a sua).',
                verbose_name='Último número de protocolo utilizado',
            ),
        ),
        migrations.AddField(
            model_name='protocoloenvio',
            name='numero_sequencial',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Sequência numérica própria do cliente (não é compartilhada entre clientes).',
                verbose_name='Número sequencial do protocolo',
            ),
        ),
        migrations.RunPython(backfill_numero_sequencial, noop),
    ]
