# Generated by Django 5.2.8 on 2026-08-27 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0009_cliente_loja_grupo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienteprotocolo',
            options={'ordering': ['codigo', 'loja', 'nome'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
