# Generated by Django 6.0.6 on 2026-10-09 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0011_flags_somente_loja_01'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagadorNd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagadores_nd', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagador de ND',
                'verbose_name_plural': 'Pagadores de ND',
                'ordering': ['nome'],
            },
        ),
    ]
