# Generated by Django 6.0.6 on 2026-10-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0012_pagador_nd'),
    ]

    operations = [
        migrations.CreateModel(
            name='TituloNd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=320, unique=True)),
                ('filial', models.CharField(blank=True, max_length=100)),
                ('cod_cliente', models.CharField(blank=True, max_length=50)),
                ('cliente', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=50)),
                ('natureza', models.CharField(blank=True, max_length=20)),
                ('emissao', models.CharField(blank=True, max_length=20)),
                ('vencimento_real', models.CharField(blank=True, max_length=20)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('historico', models.CharField(blank=True, max_length=500)),
                ('baixado', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Título de ND',
                'verbose_name_plural': 'Títulos de ND',
                'ordering': ['baixado', 'cliente', 'titulo', 'id'],
            },
        ),
    ]
