# Generated by Django 6.0.6 on 2026-08-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título interno')),
                ('caption', models.TextField(blank=True, default='', verbose_name='Legenda')),
                ('hashtags', models.CharField(blank=True, default='', max_length=500, verbose_name='Hashtags')),
                ('media_url', models.URLField(blank=True, default='', max_length=500, verbose_name='URL da mídia')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Programada'), ('published', 'Publicada'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Status')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Programado para')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
                ('criado_por', models.CharField(blank=True, default='', max_length=150, verbose_name='Criado por')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Post Instagram',
                'verbose_name_plural': 'Posts Instagram',
                'ordering': ['-scheduled_at', '-data_criacao'],
            },
        ),
    ]
