# Generated by Django 6.0.6 on 2026-08-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True, default='')),
                ('instagram_account_id', models.CharField(blank=True, default='', max_length=64)),
                ('instagram_username', models.CharField(blank=True, default='', max_length=150)),
                ('page_name', models.CharField(blank=True, default='', max_length=200)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('linked_by', models.CharField(blank=True, default='', max_length=150)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Conexão Instagram',
                'verbose_name_plural': 'Conexões Instagram',
            },
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='instagram_media_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='ID container IG'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='instagram_post_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='ID publicação IG'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='marketing/instagram/%Y/%m/', verbose_name='Arquivo de mídia'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='media_type',
            field=models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo'), ('none', 'Sem mídia')], default='none', max_length=10, verbose_name='Tipo de mídia'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='publish_error',
            field=models.TextField(blank=True, default='', verbose_name='Último erro de publicação'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='media_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='URL externa da mídia'),
        ),
    ]
