# Generated by Django 6.0.6 on 2026-08-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_instagramconnection_instagrampost_instagram_media_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='post_format',
            field=models.CharField(choices=[('feed', 'Feed'), ('reels', 'Reels'), ('story', 'Story')], default='feed', max_length=10, verbose_name='Formato'),
        ),
    ]
