# Generated by Django 6.0.6 on 2026-08-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_instagrampost_post_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='feed_aspect',
            field=models.CharField(choices=[('square', 'Quadrado 1:1'), ('portrait', 'Retrato 4:5')], default='square', max_length=10, verbose_name='Proporção do feed'),
        ),
    ]
