# Generated by Django 6.0.6 on 2026-08-10 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_instagrampost_feed_aspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='post_format',
            field=models.CharField(choices=[('feed', 'Feed'), ('carousel', 'Carrossel'), ('reels', 'Reels'), ('story', 'Story')], default='feed', max_length=10, verbose_name='Formato'),
        ),
        migrations.CreateModel(
            name='InstagramPostSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('media_url', models.URLField(blank=True, default='', max_length=500, verbose_name='URL externa')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='marketing/instagram/carousel/%Y/%m/', verbose_name='Arquivo')),
                ('media_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo'), ('none', 'Sem mídia')], default='image', max_length=10, verbose_name='Tipo')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='marketing.instagrampost', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Slide carrossel',
                'verbose_name_plural': 'Slides carrossel',
                'ordering': ['position', 'id'],
            },
        ),
    ]
