# Generated by Django 6.0.6 on 2026-09-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('J', 'Pessoa jurídica'), ('F', 'Pessoa física')], default='J', max_length=1, verbose_name='Tipo de pessoa')),
                ('cnpj', models.CharField(blank=True, default='', max_length=20, verbose_name='CNPJ/CPF')),
                ('cnpj_digits', models.CharField(blank=True, db_index=True, default='', max_length=14)),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão social / Nome')),
                ('nome_fantasia', models.CharField(blank=True, default='', max_length=200, verbose_name='Nome fantasia')),
                ('municipio', models.CharField(blank=True, default='', max_length=150, verbose_name='Município')),
                ('uf', models.CharField(blank=True, default='', max_length=2, verbose_name='UF')),
                ('logradouro', models.CharField(blank=True, default='', max_length=200)),
                ('numero', models.CharField(blank=True, default='', max_length=20)),
                ('complemento', models.CharField(blank=True, default='', max_length=80)),
                ('bairro', models.CharField(blank=True, default='', max_length=120)),
                ('cep', models.CharField(blank=True, default='', max_length=10)),
                ('telefone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('inscricao_estadual', models.CharField(blank=True, default='', max_length=20, verbose_name='Inscrição estadual')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente comercial',
                'verbose_name_plural': 'Clientes comerciais',
                'ordering': ['razao_social', 'cnpj'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cnpj_digits', ''), _negated=True), fields=('cnpj_digits',), name='comercial_cliente_cnpj_digits_uniq')],
            },
        ),
    ]
