# Generated by Django 6.0.6 on 2026-09-01 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_situacao_somente_pj'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropostaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('frete', 'Frete'), ('armazenagem', 'Armazenagem')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviada', 'Enviada'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='rascunho', max_length=20, verbose_name='Status')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor estimado')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas', to='comercial.clientecomercial', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Proposta comercial',
                'verbose_name_plural': 'Propostas comerciais',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
