# Generated by Django 5.2.8 on 2026-09-01 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_propostacomercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostacomercial',
            name='att',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Att.'),
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='cliente_nome',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Cliente (proposta)'),
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='condicoes',
            field=models.JSONField(blank=True, default=list, verbose_name='Generalidades e condições'),
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='data_proposta',
            field=models.DateField(blank=True, null=True, verbose_name='Data da proposta'),
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='faturamento',
            field=models.CharField(blank=True, default='Semanal / 30 DDL', max_length=120),
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='local_emissao',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='proposta_referente',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='reajuste',
            field=models.CharField(blank=True, default='Anual com base no índice INCT', max_length=200),
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='responsavel',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='revisao',
            field=models.CharField(blank=True, default='01', max_length=10, verbose_name='Revisão'),
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='subtitulo',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='validade',
            field=models.CharField(blank=True, default='30 dias', max_length=80),
        ),
        migrations.AddField(
            model_name='propostacomercial',
            name='vigencia',
            field=models.CharField(blank=True, default='12 meses', max_length=80, verbose_name='Vigência'),
        ),
        migrations.CreateModel(
            name='PropostaFreteLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('origem', models.CharField(blank=True, default='', max_length=120)),
                ('entrega', models.CharField(blank=True, default='', max_length=120)),
                ('devolucao_container', models.CharField(blank=True, default='', max_length=120, verbose_name='Dev. CTNR')),
                ('observacoes', models.CharField(blank=True, default='', max_length=200)),
                ('peso', models.CharField(blank=True, default='', max_length=40)),
                ('tarifa_frete', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('pedagio', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ad_valorem', models.CharField(blank=True, default='', max_length=20, verbose_name='Ad-VL')),
                ('gris', models.CharField(blank=True, default='', max_length=20, verbose_name='GRIS')),
                ('icms', models.CharField(blank=True, default='Não incluso', max_length=40)),
                ('prazo_dias', models.CharField(blank=True, default='', max_length=20)),
                ('total_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='comercial.propostacomercial')),
            ],
            options={
                'verbose_name': 'Linha de frete',
                'verbose_name_plural': 'Linhas de frete',
                'ordering': ['ordem', 'pk'],
            },
        ),
    ]
