# Generated by Django 5.2.8 on 2026-09-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0015_tabela_frete_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrizIcmsUf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriz', models.JSONField(blank=True, default=dict, verbose_name='Matriz ICMS por UF')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Matriz ICMS por UF',
                'verbose_name_plural': 'Matriz ICMS por UF',
            },
        ),
    ]
