# Generated by Django 6.0.6 on 2026-07-07 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Colaborador (Compras)',
                'verbose_name_plural': 'Colaboradores (Compras)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('unidade', models.CharField(default='Un', max_length=50, verbose_name='Unidade')),
                ('qtd_atual', models.PositiveIntegerField(default=0, verbose_name='Quantidade Atual')),
                ('qtd_minima', models.PositiveIntegerField(default=0, verbose_name='Quantidade Mínima')),
            ],
            options={
                'verbose_name': 'Item de Estoque',
                'verbose_name_plural': 'Itens de Estoque',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EntradaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_nome', models.CharField(max_length=150, verbose_name='Item (snapshot)')),
                ('data', models.DateField(verbose_name='Data da Compra')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Unitário')),
                ('fornecedor_nome', models.CharField(max_length=150, verbose_name='Fornecedor (snapshot)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='compras.fornecedor', verbose_name='Fornecedor')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='compras.itemestoque', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Entrada de Estoque',
                'verbose_name_plural': 'Entradas de Estoque',
                'ordering': ['-data', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SaidaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_nome', models.CharField(max_length=150, verbose_name='Item (snapshot)')),
                ('data', models.DateField(verbose_name='Data da Saída')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('setor_nome', models.CharField(max_length=100, verbose_name='Setor (snapshot)')),
                ('colaborador_nome', models.CharField(max_length=150, verbose_name='Colaborador (snapshot)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas', to='compras.colaborador', verbose_name='Colaborador')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas', to='compras.itemestoque', verbose_name='Item')),
                ('setor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas', to='compras.setor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Saída de Estoque',
                'verbose_name_plural': 'Saídas de Estoque',
                'ordering': ['-data', '-data_criacao'],
            },
        ),
    ]
